name: Jupyter_Analyses
channels:
  - defaults
dependencies:
  - python=3.11
  - pandas=2.2.2
  - ipykernel=6.28.0
  - ipython=8.27.0
  - jupyter
  - matplotlib=3.9.2
  - plotly=6.0.1
  - seaborn=0.13.2

